include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
    lines_longer_than_80_chars: false
    parameter_assignments: ignore
    public_member_api_docs: ignore
    use_string_buffers: ignore